# Generated by Django 4.2.7 on 2023-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_tbl_booking_tbl_event_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('food', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='price',
        ),
    ]
