# Generated by Django 4.2.6 on 2023-12-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_tbl_category_remove_tbl_event_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_category',
            old_name='type',
            new_name='category_type',
        ),
    ]
