# Generated by Django 4.2.6 on 2023-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_type_tbl_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_event',
            name='date',
            field=models.CharField(default='eee', max_length=50),
            preserve_default=False,
        ),
    ]
