# Generated by Django 4.2.6 on 2023-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_food_tbl_event_time_tbl_event_people_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_event',
            name='status',
            field=models.CharField(default='www', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_event',
            name='user_id',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
    ]
