# Generated by Django 4.0.4 on 2023-12-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_tbl_event_status_tbl_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_event',
            name='total_amount',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
