# Generated by Django 4.2.7 on 2024-01-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_tbl_category_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
